package br.com.fiap.sociallearn.domain.exceptions

enum class GenericException {
    GENERIC_ERROR,
    ERROR_INVALID_CUSTOM_TOKEN,
    ERROR_CUSTOM_TOKEN_MISMATCH,
    ERROR_INVALID_CREDENTIAL,
    ERROR_INVALID_EMAIL,
    ERROR_WRONG_PASSWORD,
    ERROR_USER_MISMATCH,
    ERROR_REQUIRES_RECENT_LOGIN,
    ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL,
    ERROR_EMAIL_ALREADY_IN_USE,
    ERROR_CREDENTIAL_ALREADY_IN_USE,
    ERROR_USER_DISABLED,
    ERROR_USER_TOKEN_EXPIRED,
    ERROR_USER_NOT_FOUND,
    ERROR_INVALID_USER_TOKEN,
    ERROR_OPERATION_NOT_ALLOWED,
    ERROR_WEAK_PASSWORD
}